export default function Head() {
  return (
    <>
      <title>Landing Page</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <link
            href="https://fonts.googleapis.com/css2?family=Dongle:wght@700&family=Island+Moments&family=Manrope:wght@200;300;400;500;600&family=Mochiy+Pop+P+One&family=Parisienne&family=Tillana&family=Urbanist:wght@100&display=swap" rel="stylesheet"
          />
      
    </>
  )
}
